// Dữ liệu câu lạc bộ
const clubsData = [
  // NGHỆ THUẬT
  {
    id: "music",
    name: "Câu Lạc Bộ Âm Nhạc",
    category: "arts",
    categoryName: "Nghệ Thuật",
    shortDesc: "Nơi âm nhạc kết nối tâm hồn",
    description:
      "CLB Âm Nhạc là nơi các bạn học sinh có đam mê với âm nhạc có thể giao lưu, học hỏi và phát triển tài năng. Chúng tôi tổ chức các buổi hòa nhạc, workshop và dự án sáng tác âm nhạc.",
    image: "img/music.jpg",
    schedule: "Thứ 3 & Thứ 6, 16:00 - 18:00",
    location: "Phòng Âm Nhạc - Tầng 3",
    members: 45,
    tags: ["Vocal", "Nhạc cụ", "Sáng tác", "Biểu diễn"],
    achievements: [
      "Giải Nhất Hội diễn Văn nghệ Học sinh 2024",
      "Top 3 cuộc thi Tài năng trẻ thành phố",
      "Tổ chức 5 buổi hòa nhạc từ thiện",
    ],
    activities: [
      "Workshop âm nhạc hàng tháng",
      "Luyện tập nhóm và solo",
      "Tổ chức mini concert",
      "Giao lưu với CLB âm nhạc các trường",
    ],
    mentor: "Thầy Nguyễn Văn A",
    contactEmail: "music.club@school.edu.vn",
  },
  {
    id: "media",
    name: "Câu Lạc Bộ Truyền Thông",
    category: "arts",
    categoryName: "Nghệ Thuật",
    shortDesc: "Kể câu chuyện qua ống kính và ngòi bút",
    description:
      "CLB Truyền Thông đào tạo kỹ năng làm báo, quay phim, chụp ảnh và thiết kế đồ họa. Chúng tôi phụ trách truyền thông cho các sự kiện của trường và sản xuất nội dung sáng tạo.",
    image: "img/media.jpg",
    schedule: "Thứ 4 & Thứ 7, 15:00 - 17:00",
    location: "Phòng Media Lab - Tầng 2",
    members: 38,
    tags: ["Photography", "Video", "Graphic Design", "Writing"],
    achievements: [
      "Giải Nhì cuộc thi Phim ngắn Học sinh 2024",
      "Sản xuất 50+ video cho trường",
      "Thiết kế hơn 100 poster sự kiện",
    ],
    activities: [
      "Đào tạo kỹ năng chụp ảnh, quay phim",
      "Chỉnh sửa và hậu kỳ",
      "Sản xuất nội dung cho mạng xã hội",
      "Workshop thiết kế đồ họa",
    ],
    mentor: "Cô Trần Thị B",
    contactEmail: "media.club@school.edu.vn",
  },
  // THỂ THAO
  {
    id: "volleyball",
    name: "Câu Lạc Bộ Bóng Chuyền",
    category: "sports",
    categoryName: "Thể Thao",
    shortDesc: "Tinh thần đồng đội trên sân chuyền",
    description:
      "CLB Bóng Chuyền rèn luyện kỹ thuật và tinh thần thể thao cho các thành viên. Chúng tôi tham gia các giải đấu liên trường và tổ chức các trận giao hữu thường xuyên.",
    image: "img/volleyball.jpg",
    schedule: "Thứ 2, 4, 6: 16:30 - 18:30",
    location: "Sân Thể Thao Đa Năng",
    members: 52,
    tags: ["Nam", "Nữ", "Thi đấu", "Giao lưu"],
    achievements: [
      "Vô địch Giải Bóng chuyền Học sinh TP 2024",
      "Á quân Giải Liên trường khu vực",
      "Đào tạo 3 VĐV cấp thành phố",
    ],
    activities: [
      "Luyện tập kỹ thuật cơ bản",
      "Chiến thuật và phối hợp nhóm",
      "Thi đấu giao hữu",
      "Tham gia giải đấu liên trường",
    ],
    mentor: "Thầy Lê Văn C",
    contactEmail: "volleyball.club@school.edu.vn",
  },
  {
    id: "badminton",
    name: "Câu Lạc Bộ Cầu Lông",
    category: "sports",
    categoryName: "Thể Thao",
    shortDesc: "Nhanh nhẹn và chính xác",
    description:
      "CLB Cầu Lông giúp học sinh rèn luyện sức khỏe, nâng cao kỹ năng chơi cầu lông từ cơ bản đến nâng cao. Không khí tập luyện thân thiện, cởi mở.",
    image: "img/badminton.jpg",
    schedule: "Thứ 3, 5, 7: 16:00 - 18:00",
    location: "Nhà Thi Đấu Trong Nhà",
    members: 41,
    tags: ["Đơn", "Đôi", "Kỹ thuật", "Thể lực"],
    achievements: [
      "Giải Ba đơn nam - Giải Cầu lông Học sinh 2024",
      "Top 8 đồng đội toàn quốc",
      "15 học sinh đạt huy chương cấp thành phố",
    ],
    activities: [
      "Luyện tập cơ bản và nâng cao",
      "Sparring và thi đấu nội bộ",
      "Workshop kỹ thuật",
      "Giao lưu với CLB ngoài trường",
    ],
    mentor: "Cô Phạm Thị D",
    contactEmail: "badminton.club@school.edu.vn",
  },
  {
    id: "chess",
    name: "Câu Lạc Bộ Cờ Vua",
    category: "sports",
    categoryName: "Thể Thao",
    shortDesc: "Rèn luyện tư duy chiến lược",
    description:
      "CLB Cờ Vua không chỉ dạy cách chơi cờ mà còn phát triển tư duy logic, khả năng tập trung và giải quyết vấn đề. Phù hợp cho mọi trình độ.",
    image: "img/chess.jpg",
    schedule: "Thứ 4 & Thứ 6: 15:30 - 17:30",
    location: "Phòng Học Liệu - Tầng 1",
    members: 29,
    tags: ["Tư duy", "Logic", "Chiến thuật", "Giải đấu"],
    achievements: [
      "Vô địch Giải Cờ vua Học sinh Thành phố 2024",
      "5 thành viên đạt Cử nhân Cờ vua",
      "Tổ chức thành công Giải Cờ vua nội bộ",
    ],
    activities: [
      "Học khai cuộc và tàn cuộc",
      "Phân tích ván đấu kinh điển",
      "Giải đấu nội bộ hàng tháng",
      "Tham gia giải cờ online và offline",
    ],
    mentor: "Thầy Hoàng Văn E",
    contactEmail: "chess.club@school.edu.vn",
  },
  {
    id: "multi-esports",
    name: "Câu Lạc Bộ eSports",
    category: "sports",
    categoryName: "Thể Thao",
    shortDesc: "Nơi hội tụ nhiều thành viên cho mọi đam mê",
    description:
      "CLB eSports tổ chức các hoạt động đa dạng: Liên Quân, Free Fire, PUBG mobile,... Phù hợp cho các bạn giải trí sau những giờ học căn thẳng.",
    image: "img/esports.jpg",
    schedule: "Chủ Nhật: 07:00 - 09:00 và 14:00 - 15:30",
    location: "Khu vự Giải Trí",
    members: 1000,
    tags: ["Liên Quân", "Free fire", "PUBG mobile"],
    achievements: [
      "Tổ chức các trận giao hữu thành công",
      "Giải Nhất Liên Quân liên trường",
      "Hơn 100 học sinh tham gia hoạt động định kỳ",
    ],
    activities: [
      "Các buổi giao hữu vui vẻ",
      "Giải toả căng thẳng sau những giờ học",
    ],
    mentor: "Thầy Nguyễn Văn F",
    contactEmail: "sports.club@school.edu.vn",
  },
];

// Dữ liệu sự kiện
const eventsData = [
  {
    id: 1,
    title: "Đại Hội Thể Thao 26/3",
    date: "2026-03-26",
    time: "07:00",
    location: "Sân trường & Hội trường",
    description:
      "Chuỗi hoạt động bóng truyền, trò chơi dân gian chào mừng ngày thành lập Đoàn TNCS Hồ Chí Minh.",
    image: "img/event-thethao.jpg",
    category: "arts",
    status: "upcoming",
  },
  {
    id: 2,
    title: "Chào Mừng 30/4 - 1/5",
    date: "2026-04-25",
    time: "08:00",
    location: "Sân trường",
    description:
      "học sinh toàn trường kỷ niệm ngày Giải phóng miền Nam và Quốc tế Lao động.",
    image: "img/event-chaomung.jpg",
    category: "sports",
    status: "upcoming",
  },
  {
    id: 3,
    title: "Lễ Tổng Kết Năm Học 2025-2026",
    date: "2026-05-31",
    time: "07:30",
    location: "Sân trường",
    description:
      "Buổi lễ trang trọng tổng kết năm học, vinh danh các cá nhân và tập thể xuất sắc, chia tay học sinh khối 12.",
    image: "img/event-tongket.jpg",
    category: "arts",
    status: "upcoming",
  },
];
